server:
    port: 8080
    sessionTimeout: 1440
    tomcat:
      max-threads: 50
      uri-encoding: UTF-8

logging:
    level:
        com.c.j.w: DEBUG
    path: ./
spring:
  profiles:
    active: dev

# 开发
---
spring:
  profiles: dev
jdbc:
    driverClassName: com.mysql.jdbc.Driver
    main:
        url: jdbc:mysql://localhost:3306/sports_dev?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true
        userName: dev
        password: 123456
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        #配置初始化大小、最小、最大
        initialSize: 1
        minIdle: 1
        maxActive: 20
        #配置获取连接等待超时的时间
        maxWait: 60000
        #配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
        timeBetweenEvictionRunsMillis: 60000
        #配置一个连接在池中最小生存的时间，单位是毫秒
        minEvictableIdleTimeMillis: 300000

# 测试
---
spring:
  profiles: test

# 正式
---
spring:
  profiles: release
